# Generated by Django 3.1.7 on 2021-03-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mfgd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
        migrations.CreateModel(
            name='CanAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canManage', models.BooleanField(default=False)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfgd_app.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfgd_app.userprofile')),
            ],
            options={
                'unique_together': {('user', 'repo')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='repositories',
            field=models.ManyToManyField(through='mfgd_app.CanAccess', to='mfgd_app.Repository'),
        ),
    ]
