# Generated by Django 3.1.7 on 2021-03-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfgd_app', '0002_auto_20210305_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canaccess',
            options={'verbose_name_plural': 'CanAccess'},
        ),
    ]
