# Generated by Django 3.1.7 on 2021-03-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfgd_app', '0003_auto_20210305_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='path',
            field=models.TextField(blank=True),
        ),
    ]
